DROP TABLE IF EXISTS person;
CREATE TABLE person(
    person_id INT PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    surname VARCHAR(20) NOT NULL,
    age INT NOT NULL CHECK(age >= 0 AND age < 150),
    birth_date DATE,
    address VARCHAR(25),
    salary REAL
);

CREATE TABLE car(
    car_id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    owner_id INT,
    brand VARCHAR(20),
    manufactureYear INT,
    CONSTRAINT fk_owner FOREIGN KEY(owner_id)
        REFERENCES person(person_id)
);

-- DROP TABLE IF EXISTS color;
-- CREATE TABLE color (
--     color_id INT GENERATED BY DEFAULT AS IDENTITY,
--     color_name VARCHAR NOT NULL,
--     PRIMARY KEY (color_id /*, color_name */)
-- );

-- CREATE TABLE color (
--     color_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     color_name VARCHAR NOT NULL
-- );

-- table vlastnik
    -- id_vlastnik
-- table nehnutelnost
    -- id_nehnutelnost
-- m:n vztah
-- vlastnik_nehnutelnost
    -- id_vlastnik
    -- id_nehnutelnost
    -- PK(id_vlastnik, id_nehnutelnost)